# Site settings
title: Keyang Xu's HomePage
description: Keyang Xu's Homepage
favicon: /assets/img/avatar.JPG
baseurl:
url: http://rivercold.github.io
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Keyang Xu
  title: Language Technology Institute
  address: Carnegie Mellon University
  email: keyangx at cs dot cmu dot edu
  link: http://rivercold.github.io
  github: rivercold
  gavatar: /assets/img/avatar.JPG
  
  educationHistory:
    - education1:
      organization: Carnegie Mellon University
      degree: Master
      major: Computer Science
      started: 2015
      duration: (2015.8 - 2017.6(estimated))
      description: Research oriented program.
    - education2:
      organization: Beihang University
      degree: Bachelor
      major: Software Engineering
      started: 2011
      duration: (2011.9 - 2015.6)
      description: GPA 3.90/4.0; Rank 1/138
  workHistory:
    - work1:
      company: Information Retrieval Group, Tsinghua University
      location: Beijing, China
      title: Research Assistant
      advisor: Dr.Yiqun Liu
      started: 2014
      duration: (2013.8 - 2015.7)
      description: My research interests foucused on Information Retrieval and Text Mining.
    - work1:
      company: School of Information, University of Michigan
      location: Ann Arbor, USA
      title: Research Assistant
      advisor: Dr.Qiaozhu Mei
      started: 2014
      duration: (2014.7 - 2014.9)
      description: I worked text minning project on medical corpora.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: Some new languages!
      percentage: 100%
    - skill3: 
      name: HTML/JavaScript/CSS
      percentage: 80%
    - skill4:
      name: Ruby
      percentage: 80%
    - skill5:
      name: Java
      percentage: 80%
