# Site settings
title: Chengzhen Wang's HomePage
description: Chengzhen Wang's Homepage
favicon: /assets/img/avatar.JPG
baseurl:
url: http://freechengzhen.github.io
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Chengzhen Wang
  title: Coder
  address: Los Angeles, California
  email: freechengzhen@gmail.com
  link: http://freechengzhen.github.io
  weibo: 再见_西尔维
  github: freechengzhen
  linkedin: ddbullfrog
  twitter: freechengzhen
  gavatar: /assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: University of Southern California
      degree: Master
      major: Computer Science
      started: 2015
      duration: (2015 - 2017)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: C++
      percentage: 90%
    - skill3: 
      name: JavaScript
      percentage: 80%
    - skill4:
      name: Python
      percentage: 80%
    - skill5:
      name: HTML/CSS
      percentage: 90%
