# Site settings
title: Keyang Xu's HomePage
description: Keyang Xu's Homepage
favicon: /assets/img/avatar.JPG
baseurl:
url: http://freechengzhen.github.io
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Keyang Xu
  title: Developer
  address: Los Angeles, California
  email: freechengzhen@gmail.com
  link: http://freechengzhen.github.io
  weibo: 再见_西尔维
  github: freechengzhen
  twitter: freechengzhen
  gavatar: /assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Tsinghua-Waterloo Joint Research Center for Internet Information
      location: Beijing, China
      title: Research Assistant
      started: 2014
      duration: (2014.4 - 2015.6)
      description: I did some NLP work and developed a data mining website using SSH Framework.
  educationHistory:
    - education1:
      organization: University of Southern California
      degree: Master
      major: Computer Science
      started: 2015
      duration: (2015.8 - 2017.6)
      description: I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: Beihang University
      degree: Bachelor
      major: Software Engineering
      started: 2011
      duration: (2011.9 - 2015.7)
      description: I had been studying here for 4 years.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: C++
      percentage: 90%
    - skill3: 
      name: HTML/JavaScript/CSS
      percentage: 80%
    - skill4:
      name: Python
      percentage: 80%
